trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Python telepítése
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # 2. Függőségek telepítése
    - script: |
        python -m pip install --upgrade pip
        pip install pytest
        pytest
      displayName: 'Install dependencies'

